<a href="https://colab.research.google.com/github/Abhinavnair13/Airport-Cab-Analysis/blob/main/Airport_Cab_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
taxi_data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/nyc_taxis.csv',delimiter=',',skip_header=True)

In [ ]:
print(taxi_data)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


#Q1) Find mean of speed of cabs

There is no speed column in the dataset so we have to calculate speed from trip distance and trip length.

In [ ]:
speed = taxi_data[:,7]/(taxi_data[:,8]/3600)
print(speed)

[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]


In [ ]:
mean_speed = speed.mean()
print(mean_speed)

32.24258580925573


#Q2) Calculate the number of rides taken in the month of februrary

In [ ]:
taxi_data[taxi_data[:,1] == 2,1]
# == 2,1] the 1 here returns only the value of the column , otherwise we will be getting all column value for that particular row

array([2., 2., 2., ..., 2., 2., 2.])

In [ ]:
rides_feb = taxi_data[taxi_data[:,1] == 2].shape[0]
print(rides_feb)

13333


#Q3) Number of rides where tip was greater than $50

In [ ]:
tip = taxi_data[taxi_data[:,-3] > 50,-3]
#tip column is -3 from right
print(tip.shape[0])

16


#Q4) Calculate the number of rides where the drop was JFK airport(dropoff_location_code=2)

In [ ]:
JFK_rides = taxi_data[taxi_data[:,6]==2,6]
print(JFK_rides.shape[0])

11832
